FROM node:16-alpine as build

WORKDIR /app/frontend

COPY package*.json ./
RUN npm ci --production
COPY . .
RUN npm run build


FROM nginx:latest

COPY --from=build /app/frontend/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]