# Generated by Django 4.1.7 on 2023-03-28 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('avatar', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('is_activated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Seniority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seniorities', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('points', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSeniority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemon')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('seniority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seniority')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='seniorities',
            field=models.ManyToManyField(through='api.ProfileSeniority', to='api.seniority'),
        ),
        migrations.CreateModel(
            name='DeveloperRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.developer')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField()),
                ('entrance_date', models.DateField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.developer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('seniority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seniority')),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='profiles',
            field=models.ManyToManyField(through='api.DeveloperProfile', to='api.profile'),
        ),
        migrations.AddField(
            model_name='developer',
            name='requirements',
            field=models.ManyToManyField(through='api.DeveloperRequirement', to='api.requirement'),
        ),
        migrations.AddConstraint(
            model_name='seniority',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='seniority',
            constraint=models.UniqueConstraint(fields=('level', 'organization'), name='unique_level_per_org'),
        ),
        migrations.AlterUniqueTogether(
            name='seniority',
            unique_together={('name', 'level', 'organization')},
        ),
    ]
