# Generated by Django 4.1.7 on 2023-03-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSeniorityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_seniority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profileseniority')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requirement')),
            ],
            options={
                'unique_together': {('profile_seniority', 'requirement')},
            },
        ),
        migrations.AddField(
            model_name='profileseniority',
            name='requirements',
            field=models.ManyToManyField(through='api.ProfileSeniorityRequirement', to='api.requirement'),
        ),
    ]
