# Generated by Django 4.1.7 on 2023-05-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
