# Generated by Django 4.1.7 on 2023-03-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='small_image',
            field=models.URLField(),
        ),
    ]
