# Generated by Django 4.1.7 on 2023-03-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profileseniorityrequirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='profileseniority',
            unique_together={('seniority', 'profile', 'pokemon')},
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('name', 'organization')},
        ),
        migrations.AddConstraint(
            model_name='profileseniority',
            constraint=models.UniqueConstraint(fields=('pokemon', 'seniority'), name='unique_pokemon_per_seniority'),
        ),
        migrations.AddConstraint(
            model_name='profileseniority',
            constraint=models.UniqueConstraint(fields=('seniority', 'profile'), name='unique_seniority_per_profile'),
        ),
    ]
