# Generated by Django 4.1.7 on 2023-03-24 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pokemon_image_alter_pokemon_small_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.organization'),
            preserve_default=False,
        ),
    ]
