# Generated by Django 4.1.7 on 2023-03-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profileseniority',
            name='unique_pokemon_per_seniority',
        ),
        migrations.AddConstraint(
            model_name='profileseniority',
            constraint=models.UniqueConstraint(fields=('pokemon', 'profile'), name='unique_pokemon_per_profile'),
        ),
    ]
