# Generated by Django 4.1.7 on 2023-06-11 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_requestjoinprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requestvalidaterequirement')),
            ],
        ),
    ]
