# Generated by Django 4.1.7 on 2023-03-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seniority_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.organization'),
            preserve_default=False,
        ),
    ]
