# Generated by Django 4.1.7 on 2023-06-12 17:37

import api.models.validate_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_developerrequirement_is_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatefile',
            name='file',
            field=models.FileField(upload_to=api.models.validate_file.upload_to),
        ),
    ]
