# Generated by Django 4.1.7 on 2023-03-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_requirement_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.URLField(),
        ),
    ]
