# Generated by Django 4.1.7 on 2023-03-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_seniorities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='seniorities',
        ),
    ]
