# Generated by Django 4.1.7 on 2023-03-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_seniority_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seniority',
            constraint=models.UniqueConstraint(fields=('name', 'level', 'organization'), name='unique_seniority'),
        ),
    ]
