# Generated by Django 4.1.7 on 2023-03-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_seniorities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seniority',
            old_name='name',
            new_name='seniority',
        ),
    ]
