# Generated by Django 4.1.7 on 2023-03-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_seniority_unique_seniority'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seniority',
            name='unique_seniority',
        ),
        migrations.AddConstraint(
            model_name='seniority',
            constraint=models.UniqueConstraint(fields=('name', 'level'), name='unique_seniority'),
        ),
    ]
