# Generated by Django 4.1.7 on 2023-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_seniority_unique_seniority_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seniority',
            name='unique_seniority',
        ),
        migrations.AddConstraint(
            model_name='seniority',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='seniority',
            constraint=models.UniqueConstraint(fields=('level', 'organization'), name='unique_level_per_org'),
        ),
    ]
