# Generated by Django 4.1.7 on 2023-03-26 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_name_seniority_seniority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileseniorityrequirement',
            name='profileseniority',
        ),
        migrations.AddField(
            model_name='profileseniorityrequirement',
            name='profile_seniority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profileseniority_requirements', to='api.profileseniority'),
            preserve_default=False,
        ),
    ]
