# Generated by Django 4.1.7 on 2023-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_seniority_unique_seniority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='small_image',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
